[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nepal-Research-and-Collaboration-Center/RT2024/blob/main/Workshop_6__Numpy-and-Pandas/Workshop6_Part1_Numpy.ipynb)


# Workshop 6: Numpy and Pandas

Welcome to the first part of Workshop 6, where we will cover the basics of Numpy. In this session, we will explore Numpy arrays, their creation, and basic operations, including indexing, slicing, and manipulating arrays.

## Part 1: Numpy Basics


# Introduction to Numpy

**Numpy** (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices. Along with that, it offers a collection of high-level mathematical functions to operate on these arrays, making it an essential tool for scientific computing and data analysis.

In the context of data analysis, especially for cities like Kathmandu, Numpy can be incredibly useful for tasks such as:

- Analyzing temperature patterns across different times of the year.
- Monitoring traffic data at various intersections to optimize traffic flow.
- Processing large datasets related to pollution levels, population density, and many more.

## Why Numpy?

Here's a table summarizing some of the key reasons why Numpy is widely used:

| **Feature**                          | **Description**                                                                                  |
|--------------------------------------|--------------------------------------------------------------------------------------------------|
| **Efficient Array Computation**      | Numpy allows fast and efficient computation on arrays, enabling large-scale data processing.    |
| **Multi-Dimensional Arrays**         | Supports multi-dimensional arrays (1D, 2D, 3D, etc.), essential for various types of data.       |
| **Broadcasting**                     | Numpy can perform operations on arrays of different shapes, automatically expanding dimensions. |
| **Integration with Other Libraries** | Numpy serves as a foundation for many other scientific libraries, making it highly versatile.    |

### 1.1.	Installation:
If you don’t have Numpy installed, you can install it using pip:

In [13]:
# !pip install numpy

### 1.2.	Importing Numpy:
Import the Numpy library in your Python script or Jupyter Notebook:

In [14]:
import numpy as np

### 1.3 Example: Analyzing Temperature Data in Kathmandu

Let's start with a simple example where we analyze temperature data for a week in Kathmandu using Numpy. This will help you understand the basics of Numpy arrays and their operations.

In [11]:
import numpy as np

# Kathmandu temperature data (in degrees Celsius) over a week
temp_data = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])

# Days of the week
days_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+")
print(f"| {'Day':<10} | {'Temperature (°C)':<16} |")
print(f"+{'-'*12}+{'-'*18}+")

# Print table rows
for day, temp in zip(days_of_week, temp_data):
    print(f"| {day:<10} | {temp:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+")

+------------+------------------+
| Day        | Temperature (°C) |
+------------+------------------+
| Sunday     | 15.5             |
| Monday     | 16.8             |
| Tuesday    | 18.1             |
| Wednesday  | 17.3             |
| Thursday   | 19.2             |
| Friday     | 20.5             |
| Saturday   | 21.2             |
+------------+------------------+



## 2. Creating Numpy Arrays

Let's start by creating Numpy arrays. Numpy arrays are similar to Python lists but with added functionality and performance. Unlike Python lists, Numpy arrays are more efficient for numerical computations and are widely used in scientific computing, data analysis, and machine learning.

### 2.1 Creating a 1D Array

In [16]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


### Example: Traffic Count at Sankhamul Bridge

Let’s start with a simple example where we create a 1D array representing the number of vehicles counted at different times of the day (morning, noon, evening) crossing the at Sankhamul Bridge (Lalitpur-Kathmandu).

In [18]:
# Number of vehicles at a specific intersection in Kathmandu (morning, noon, evening)
vehicles_data = np.array([3200, 4000, 4500])
print("Vehicle Count at Different Times of the Day:")
print("Morning: ", vehicles_data[0])
print("Day    : ", vehicles_data[1])
print("Evening: ", vehicles_data[2])

Vehicle Count at Different Times of the Day:
Morning:  3200
Day    :  4000
Evening:  4500



### 2.2 Creating 2D and 3D Arrays

We can create 2D and 3D arrays, which are useful for working with matrices or tensors. Numpy also supports multi-dimensional arrays, which are essential for handling more complex data structures. For instance, a 2D array can represent data across multiple intersections or times.


In [23]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

print("-"*25)
# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)


2D Array:
 [[1 2 3]
 [4 5 6]]
-------------------------
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Example: Traffic Data at Multiple Intersections
Consider a scenario where traffic data is collected at two different intersections in Kathmandu Valley at three different times of the day (morning, noon, evening). We can represent this data as a 2D array:

In [24]:
# Traffic data at two intersections (intersection 1, intersection 2) across three time periods (morning, noon, evening)
traffic_data = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])
print("Traffic Data at Two Intersections:")
print(traffic_data)

Traffic Data at Two Intersections:
[[3200 6300]
 [4000 8800]
 [4500 6400]]


In this 2D array:

**Rows** represent different times of the day (morning, noon, evening).
**Columns** represent different intersections (Intersection 1 and Intersection 2).

This format allows for easy comparison of traffic volumes across different times and locations, which is essential for effective traffic management.

### Creating 3D Arrays

3D arrays can be used to represent even more complex datasets. For example, suppose we want to track traffic data across multiple days at multiple intersections. A 3D array can store this data efficiently.

### Example: Traffic Data Over Multiple Days

Imagine we collect traffic data at two intersections in Kathmandu over three days. We can structure this data into a 3D array where:

- **The first dimension** represents different days.
- **The second dimension** represents different times of the day.
- **The third dimension** represents different intersections.

In [25]:
# Traffic data over three days at two intersections (intersection 1, intersection 2)
traffic_data_3d = np.array([[[120, 130], [300, 280], [450, 400]],   # Day 1
                            [[130, 140], [320, 300], [460, 420]],   # Day 2
                            [[125, 135], [310, 290], [455, 410]]])  # Day 3

print("Traffic Data Over Three Days at Two Intersections:")
print(traffic_data_3d)

Traffic Data Over Three Days at Two Intersections:
[[[120 130]
  [300 280]
  [450 400]]

 [[130 140]
  [320 300]
  [460 420]]

 [[125 135]
  [310 290]
  [455 410]]]



### 2.3 Analyzing Environmental Data (1.3 Extension)

Let’s consider another example where we create an array to represent temperature data collected from three different monitoring stations around Kathmandu over a week. This data can help in analyzing micro-climate variations across the city.

#### Example: Temperature Data from Multiple Stations

In [28]:
# Temperature data from three stations in Kathmandu over a week (each row represents a day)
temperature_data = np.array([[15.5, 16.1, 15.8],
                             [16.8, 17.3, 16.9],
                             [18.1, 18.6, 18.0],
                             [17.3, 17.8, 17.4],
                             [19.2, 19.7, 19.1],
                             [20.5, 21.0, 20.6],
                             [21.2, 21.7, 21.3]])

# Days of the week
days_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")
print(f"| {'Day':<10} | {'Station 1 (°C)':<16} | {'Station 2 (°C)':<16} | {'Station 3 (°C)':<16} |")
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")

# Print table rows
for day, temps in zip(days_of_week, temperature_data):
    print(f"| {day:<10} | {temps[0]:<16} | {temps[1]:<16} | {temps[2]:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")

+------------+------------------+------------------+------------------+
| Day        | Station 1 (°C)   | Station 2 (°C)   | Station 3 (°C)   |
+------------+------------------+------------------+------------------+
| Sunday     | 15.5             | 16.1             | 15.8             |
| Monday     | 16.8             | 17.3             | 16.9             |
| Tuesday    | 18.1             | 18.6             | 18.0             |
| Wednesday  | 17.3             | 17.8             | 17.4             |
| Thursday   | 19.2             | 19.7             | 19.1             |
| Friday     | 20.5             | 21.0             | 20.6             |
| Saturday   | 21.2             | 21.7             | 21.3             |
+------------+------------------+------------------+------------------+



## 3. Array Operations

Numpy allows you to perform element-wise operations on arrays, making mathematical computations efficient.

### 3.1 Element-wise Operations


In [ ]:

# Element-wise addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result_add = array_a + array_b
print("Element-wise Addition:", result_add)

# Element-wise multiplication
result_mult = array_a * array_b
print("Element-wise Multiplication:", result_mult)



### 3.2 Broadcasting in Numpy

Numpy supports broadcasting, allowing you to perform operations on arrays of different shapes.


In [ ]:

# Broadcasting example
array_c = np.array([1, 2, 3])
array_d = np.array([[4], [5], [6]])
result_broadcast = array_c + array_d
print("Broadcasting Result:\n", result_broadcast)



## 4. Indexing and Slicing

Indexing and slicing in Numpy arrays work similarly to Python lists but with more powerful features.

### 4.1 Accessing Elements


In [ ]:

# Accessing elements in a 2D array
element = array_2d[1, 2]  # 2nd row, 3rd column
print("Element at 2nd row, 3rd column:", element)



### 4.2 Slicing Arrays

You can slice Numpy arrays to access subarrays.


In [ ]:

# Slicing a 2D array
sub_array = array_2d[:, 1:3]  # All rows, 2nd to 3rd columns
print("Sliced Array:\n", sub_array)



## 5. Array Manipulation

Numpy provides several functions to manipulate arrays, such as reshaping, joining, and splitting arrays.

### 5.1 Reshaping Arrays


In [ ]:

# Reshaping a 1D array to a 2D array
reshaped_array = array_1d.reshape(1, 5)
print("Reshaped Array:\n", reshaped_array)



### 5.2 Joining and Splitting Arrays


In [ ]:

# Joining two arrays
joined_array = np.concatenate((array_a, array_b))
print("Joined Array:", joined_array)

# Splitting an array
split_array = np.array_split(joined_array, 3)
print("Split Arrays:", split_array)
